### ISSUE TITLE
server IP is use instead of user IP

### ISSUE THREAD

**Issue by rnunez80** [collective/Products.PloneSurvey#15]
if you have your frontend (proxy, loadbalancer, caching) on a separate server, all incoming surveys will have a cookie/user with the server ip address instead of the real ip address. the issue is that ip_address in Survey.py is checking for 127.0.0.1 in REMOTE_ADDR first then using HTTP_X_FORWARDED_FOR. maybe it should check HTTP_X_FORWARDED_FOR first, if it does not exist then use REMOTE_ADDR

**Comment by keul** [comment]
Looking at the code (https://github.com/collective/Products.PloneSurvey/blob/81a6be65da19973523dc263cd9430c188faaf9f6/Products/PloneSurvey/content/Survey.py#L419) The product is using `request.getClientAddr` which is the right way to do.

Read the following SO question. I think that something must be done in your environment: http://stackoverflow.com/questions/5170364/how-do-i-configure-my-web-server-to-work-with-the-pluggableauthservices-domain
