### ISSUE TITLE
Error when add subsurvey

### ISSUE THREAD

**Issue by rogeriocdluiz** [collective/Products.PloneSurvey#20]
I get the error below whey i try to add a subsurvey. Subsurvey are created only in a empty survey. 

---------------------------------------

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.FactoryTool, line 478, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 32, in _call
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
   - Warning: Macro expansion failed
   - Warning: <type 'exceptions.KeyError'>: 'macro'
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 522, in do_optTag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
  Module zope.tales.tales, line 696, in evaluate
   - URL: file:/opt/plone437/buildout-cache/eggs/Products.Archetypes-1.9.10-py2.7.egg/Products/Archetypes/skins/archetypes/widgets/selection.pt
   - Line 37, Column 12
   - Expression: <PythonExpr field.Vocabulary(context)>
   - Names:
      {'container': <PloneSite at /intranet>,
       'context': <SubSurvey at /intranet/servicos/questionarios/canal-aberto/portal_factory/Sub Survey/sub_survey.2015-11-16.0238685869 used for /intranet/servicos/questionarios/canal-aberto>,
       'default': <object object at 0x7f9fd00ba520>,
       'here': <SubSurvey at /intranet/servicos/questionarios/canal-aberto/portal_factory/Sub Survey/sub_survey.2015-11-16.0238685869 used for /intranet/servicos/questionarios/canal-aberto>,
       'loop': {u'field': <Products.PageTemplates.Expressions.PathIterator object at 0x7f9fb5524d50>,
                u'fieldset': <Products.PageTemplates.Expressions.PathIterator object at 0x7f9fb5472f50>},
       'nothing': None,
       'options': {'args': (),
                   'state': <Products.CMFFormController.ControllerState.ControllerState object at 0x7f9fb53864d0>},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f9fb54c3a48>,
       'request': <HTTPRequest, URL=http://xxxxxxxxxxxx:8080/intranet/servicos/questionarios/canal-aberto/portal_factory/Sub Survey/sub_survey.2015-11-16.0238685869/atct_edit>,
       'root': <Application at >,
       'template': <FSControllerPageTemplate at /intranet/atct_edit used for /intranet/servicos/questionarios/canal-aberto/portal_factory/Sub Survey/sub_survey.2015-11-16.0238685869>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>}
  Module Products.PageTemplates.ZRPythonExpr, line 48, in __call__
   - __traceback_info__: field.Vocabulary(context)
  Module PythonExpr, line 1, in <expression>
  Module Products.Archetypes.Field, line 553, in Vocabulary
  Module Products.Archetypes.utils, line 132, in mapply
  Module Products.PloneSurvey.content.SubSurvey, line 78, in getValidationQuestions
TypeError: append() takes exactly one argument (2 given)

---------------------------------------

environ
HTTP_ACCEPT	'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
CONNECTION_TYPE	'keep-alive'
HTTP_USER_AGENT	'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0'
HTTP_REFERER	'http://xxxxxxxxxxxx:8080/intranet/servicos/questionarios/canal-aberto'
SERVER_NAME	'debian.prdf.mpf.mp.br'
GATEWAY_INTERFACE	'CGI/1.1'
SERVER_SOFTWARE	'Zope/(2.13.23, python 2.7.9, linux2) ZServer/1.1'
REMOTE_ADDR	'xxxxxxxxxxxx'
HTTP_ACCEPT_LANGUAGE	'pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3'
SCRIPT_NAME	''
plone.protect.safe_oids	[None]
REQUEST_METHOD	'GET'
HTTP_HOST	'xxxxxxxxxxxx:8080'
PATH_INFO	'/intranet/servicos/questionarios/canal-aberto/portal_factory/Sub Survey/sub_survey.2015-11-16.0238685869/edit'
SERVER_PORT	'8080'
SERVER_PROTOCOL	'HTTP/1.1'
QUERY_STRING	'_authenticator=0d7ad83452e661307866ec1d9c8edb6393caa4cc'
channel.creation_time	1447705920
HTTP_ACCEPT_ENCODING	'gzip, deflate'
HTTP_COOKIE	'tree-s="eJzT0MgpMOQKVncEAyenDGNHW3WuAiOuxJICYy49AHnZB5I"; __ac="NjE2NDZkNjk2ZTo3NDMxNjg3NTM0NmUzNDIxNDAyMw%253D%253D"; __cp="x%25DA%25AD%258C1%250E%25021%250C%2504%2523%2584%2580%2502J%25FEpM%253ECKer%250B2%25E2%251C%25C8%25FAx%253F%25CE%257D%2581%252B%25BC%25D2%25CEZ3lRJ%251A%2597%25AE%25DB%2588a%2517%25E1%25BD%25F2%25D0%2507%25F3%2526%2506_%250A%25D1%25BEZ%252Ay%258A%25F2%2599A%25D7j%25D24%25C81H%2511%2593W%2596%251B%259AWv%2597%25EB%25BB.%25BE%25CB%25FF%25BE%257D%2500%2521g%25F3%25D5%2594%25FD%257F%2582Q%251E%2598%25D6r%259E%2503%258C%2520%259E%2592%2589%25AC%2523%25CC%25F5%25AEE%25DA%250Fh%2527a%255B"'
PATH_TRANSLATED	'/intranet/servicos/questionarios/canal-aberto/portal_factory/Sub Survey/sub_survey.2015-11-16.0238685869/edit'

    Plone 4.3.7 (4311)
    CMF 2.2.9
    Zope 2.13.23
    Python 2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
    PIL 2.9.0 (Pillow)

**Comment by davismr** [comment]
This was fixed by this commit, https://github.com/collective/Products.PloneSurvey/commit/246e4adfc449f0c052cca4d6566b7ac9db2f59aa#diff-b5f9539280094bc3d7701a0ad7ddb608. Upgrade to master.

**Comment by rogeriocdluiz** [comment]
Thank you.

Em domingo, 22 de novembro de 2015, Michael Davis <notifications@github.com>
escreveu:

> Closed #20 <https://github.com/collective/Products.PloneSurvey/issues/20>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/collective/Products.PloneSurvey/issues/20#event-471473714>
> .
>


-- 



Rogério da Costa Dantas Luiz
