### ISSUE TITLE
Did we drop Plone 4.x support?

### ISSUE THREAD

**Issue by tcurvelo** [collective/Products.PloneSurvey#26]
Since merge c6e180c48e `Products.PloneSurvey` isn't Plone 4.3 compatible anymore. 
Is this a thing already? Are we just dropping 4.3 support?

~~Can we have a 1.4.9 release, at least?~~(Found it).

cc @davismr @sgeulette

**Comment by davismr** [comment]
Latest release, 1.4.9 is Plone 4.3 compatible. If someone needs to do bug fixing or feature enhancements for Plone 4.3, they can branch from the tag.
