### ISSUE TITLE
plone 4 compatiblity

### ISSUE THREAD

**Issue by frisi** [collective/Products.PloneSurvey#28]
the current changes on master after the 1.4.9 release make plonesurvey incompatible with plone4

on startup of the instance i get this error:

```
    ZopeXMLConfigurationError: File "/src/Products.PloneSurvey/Products/PloneSurvey/content/configure.zcml", line 7.2-8.31
    ImportError: cannot import name IMailSchema
```

@davismr i guess (did not look deeper into that) your plone5 branch introduced this incompatiblity.
is there an easy way to make this work for both plone versions?
or do we have to start a 1.x branch and backport other improvements (such as resetting responses) to this one too?

**Comment by frisi** [comment]
i started a branch to fix the plone4 issues, please let me know what you think of it @davismr

**Comment by davismr** [comment]
Hi Harald,

I’m reluctant to support both 4 and 5. PloneSurvey has been fairly stable for quite some time, are some of the latest fixes important for Plone4 users? I’m not sure about the take up of Plone5 either, are a significant number of users stuck on Plone4?

Cheers
Michael

**Comment by frisi** [comment]
i can't talk for other people but we have a lot of projects still running on plone4 that won't be updated to plone5 soon. currently one one of them is using plonesurvey.
i think it will be hard to get absolute numbers on this..

i tried out the master branch because i got problems when resetting respondents (and i think this is fixed with https://github.com/collective/Products.PloneSurvey/commit/eecd05a440a9e2bbc80b7c09475877b604225e99)

**Comment by davismr** [comment]
Hi Harald,

If it’s just that fix you need, probably best to just branch, and cherry pick changes from master.

Cheers
Michael

**Comment by frisi** [comment]
sure. in the long run however, there will be translations and other fixes that need to be back and forward-ported.
dunno what's more work (support both plone versions in one package, or maintain separate branches)
in my current situation both is fine. 
afaics all that's missing to support both versions is a decent test-setup

**Comment by davismr** [comment]
Hi Harald,

I’ll let you make the judgement call, as you’ll probably be doing most of the work anyway.

Cheers
Michael

**Comment by frisi** [comment]
thanks @davismr 
i started a 1.x branch today, and will implement some fixes for the bugreports i receive from our customer.
you can port them to master if they apply there too.
do you want me to create merge requests for all of them, or can i commit directly to the 1.x branch?

would you add me as a maintainer on pypi (user frisi) or shall i ask you for a release when i'm finished with my tasks?

**Comment by frisi** [comment]
@davismr 
could you please answer my question about the merge-requests/review process for 1.x (i already pushed some fixes for encoding issues) and the pypi privileges?
i'd like to make a release today

**Comment by davismr** [comment]
Hi Harold,

Apologies, I missed your email. Just commit direct to the branch, don't worry about pull requests. I'll cherry pick commits to master. I'll sort out pypi permissions later today.

Cheers
Michael

**Comment by davismr** [comment]
Hi Harald,

You should have permissions on pypi now.

Cheers
Michael

**Comment by frisi** [comment]
thanks michael
release is done. i added a note about plone5 support to the readme
this issue can be closed.
